import { useState, useMemo } from 'react';
import { motion } from 'framer-motion';
import { FaSearch, FaBook, FaLightbulb } from 'react-icons/fa';

const Glossary = () => {
  const [searchTerm, setSearchTerm] = useState('');
  const [simpleMode, setSimpleMode] = useState(false);
  const [selectedCategory, setSelectedCategory] = useState('all');

  const glossaryTerms = useMemo(() => [
    {
      term: 'EPS (Earnings Per Share)',
      category: 'Profitability',
      definition: 'A company\'s net profit divided by the number of outstanding shares. It shows how much profit is allocated to each share of stock.',
      simple: 'If a pizza shop makes $100 profit and has 10 owners, each owner\'s share is worth $10. That\'s basically EPS!',
      example: 'If Apple makes $90 billion and has 15 billion shares, EPS = $90B ÷ 15B = $6 per share',
      formula: 'EPS = Net Income ÷ Shares Outstanding'
    },
    {
      term: 'P/E Ratio (Price-to-Earnings)',
      category: 'Valuation',
      definition: 'The ratio of a company\'s stock price to its earnings per share. It indicates how much investors are willing to pay per dollar of earnings.',
      simple: 'If a lemonade stand costs $100 but makes $10 per year, the P/E is 10. It takes 10 years of profits to "pay back" your investment.',
      example: 'Stock at $150 with $10 EPS has P/E = 150 ÷ 10 = 15',
      formula: 'P/E Ratio = Stock Price ÷ EPS'
    },
    {
      term: 'Market Cap (Market Capitalization)',
      category: 'Valuation',
      definition: 'The total market value of a company\'s outstanding shares. It represents what the market thinks the entire company is worth.',
      simple: 'If you could buy the entire company, this is roughly what you\'d pay. Like the "price tag" for the whole business.',
      example: '1 million shares × $50 per share = $50 million market cap',
      formula: 'Market Cap = Share Price × Total Shares Outstanding'
    },
    {
      term: 'EBITDA',
      category: 'Profitability',
      definition: 'Earnings Before Interest, Taxes, Depreciation, and Amortization. A measure of operating performance before financing and accounting decisions.',
      simple: 'How much money the business makes from its actual operations, before paying loans, taxes, or accounting for stuff wearing out.',
      example: '$100M revenue - $60M operating costs = $40M EBITDA',
      formula: 'EBITDA = Operating Income + Depreciation + Amortization'
    },
    {
      term: 'ROE (Return on Equity)',
      category: 'Efficiency',
      definition: 'Net income as a percentage of shareholder equity. Measures how efficiently a company uses shareholders\' investments to generate profit.',
      simple: 'If you give a company $100 and they make $15 profit, that\'s 15% ROE. Shows how good they are at using your money.',
      example: '$50M profit ÷ $300M equity = 16.7% ROE',
      formula: 'ROE = (Net Income ÷ Shareholder Equity) × 100'
    },
    {
      term: 'ROA (Return on Assets)',
      category: 'Efficiency',
      definition: 'Net income as a percentage of total assets. Indicates how efficiently a company uses its assets to generate profit.',
      simple: 'Shows how good a company is at using everything it owns (buildings, equipment, money) to make profit.',
      example: '$50M profit ÷ $500M assets = 10% ROA',
      formula: 'ROA = (Net Income ÷ Total Assets) × 100'
    },
    {
      term: 'ROIC (Return on Invested Capital)',
      category: 'Efficiency',
      definition: 'Measures how well a company generates returns from all capital invested in the business, both equity and debt.',
      simple: 'Like ROE but includes borrowed money too. Shows how well they use ALL the money invested, not just shareholder money.',
      example: '$50M profit ÷ $400M invested capital = 12.5% ROIC',
      formula: 'ROIC = Net Operating Profit ÷ Invested Capital'
    },
    {
      term: 'Free Cash Flow (FCF)',
      category: 'Cash Flow',
      definition: 'Cash generated by operations minus capital expenditures. The cash available for distribution to investors or reinvestment.',
      simple: 'Money left over after paying for everything needed to keep the business running. This is "real" spendable money.',
      example: '$100M operating cash - $30M equipment purchases = $70M FCF',
      formula: 'FCF = Operating Cash Flow - Capital Expenditures'
    },
    {
      term: 'Debt-to-Equity Ratio',
      category: 'Leverage',
      definition: 'Total debt divided by shareholder equity. Measures financial leverage and indicates how much debt a company uses relative to equity.',
      simple: 'Compares borrowed money to owned money. If it\'s 2.0, the company borrowed twice as much as owners put in.',
      example: '$60M debt ÷ $40M equity = 1.5 debt-to-equity ratio',
      formula: 'Debt-to-Equity = Total Debt ÷ Shareholder Equity'
    },
    {
      term: 'Current Ratio',
      category: 'Liquidity',
      definition: 'Current assets divided by current liabilities. Measures a company\'s ability to pay short-term obligations.',
      simple: 'Can the company pay its bills this year? If current ratio is 2.0, they have $2 for every $1 they owe soon.',
      example: '$200M current assets ÷ $100M current liabilities = 2.0',
      formula: 'Current Ratio = Current Assets ÷ Current Liabilities'
    },
    {
      term: 'Dividend Yield',
      category: 'Returns',
      definition: 'Annual dividends per share divided by stock price. Shows the percentage return from dividends alone.',
      simple: 'Like interest on a savings account. If yield is 3%, you get $3 per year for every $100 invested (plus stock price changes).',
      example: '$4 annual dividend ÷ $100 stock price = 4% yield',
      formula: 'Dividend Yield = (Annual Dividend per Share ÷ Stock Price) × 100'
    },
    {
      term: 'PEG Ratio',
      category: 'Valuation',
      definition: 'P/E ratio divided by earnings growth rate. Accounts for growth when evaluating valuation.',
      simple: 'P/E ratio adjusted for growth. A fast-growing company can justify a high P/E. PEG under 1.0 might be a good deal.',
      example: 'P/E of 30 ÷ 25% growth rate = PEG of 1.2',
      formula: 'PEG = P/E Ratio ÷ Annual EPS Growth Rate'
    },
    {
      term: 'Book Value',
      category: 'Valuation',
      definition: 'Total assets minus total liabilities. Represents the net asset value of the company.',
      simple: 'If you sold everything the company owns and paid all debts, this is what would be left over for shareholders.',
      example: '$500M assets - $200M liabilities = $300M book value',
      formula: 'Book Value = Total Assets - Total Liabilities'
    },
    {
      term: 'Beta',
      category: 'Risk',
      definition: 'A measure of a stock\'s volatility relative to the overall market. Beta > 1 means more volatile than market.',
      simple: 'Shows how wild the stock price swings. Beta of 1.5 means if market moves 10%, this stock typically moves 15%.',
      example: 'Beta of 0.8 = less volatile than market; Beta of 1.5 = more volatile',
      formula: 'Calculated using statistical regression against market returns'
    },
    {
      term: 'CAPEX (Capital Expenditures)',
      category: 'Cash Flow',
      definition: 'Money spent on acquiring or upgrading physical assets like buildings, equipment, or technology.',
      simple: 'Buying long-term stuff like factories, computers, or delivery trucks. Not day-to-day expenses.',
      example: 'Buying new manufacturing equipment for $10M is CAPEX',
      formula: 'CAPEX = PP&E (end) - PP&E (start) + Depreciation'
    },
    {
      term: 'Gross Margin',
      category: 'Profitability',
      definition: 'Revenue minus cost of goods sold, expressed as a percentage of revenue. Shows profitability before operating expenses.',
      simple: 'If you sell a shirt for $20 that cost $8 to make, gross margin is 60%. Higher is usually better.',
      example: '$100M revenue - $40M COGS = 60% gross margin',
      formula: 'Gross Margin = ((Revenue - COGS) ÷ Revenue) × 100'
    },
    {
      term: 'Operating Margin',
      category: 'Profitability',
      definition: 'Operating income divided by revenue. Shows profitability from core operations.',
      simple: 'After paying to make products AND run the business (salaries, rent, ads), what % of sales is profit?',
      example: '$30M operating income ÷ $100M revenue = 30% operating margin',
      formula: 'Operating Margin = (Operating Income ÷ Revenue) × 100'
    },
    {
      term: 'Net Margin',
      category: 'Profitability',
      definition: 'Net income divided by revenue. The percentage of revenue that becomes actual profit.',
      simple: 'The "bottom line." After paying for EVERYTHING (including taxes and interest), what % is left as profit?',
      example: '$15M net income ÷ $100M revenue = 15% net margin',
      formula: 'Net Margin = (Net Income ÷ Revenue) × 100'
    }
  ], []);

  const categories = ['all', ...new Set(glossaryTerms.map(term => term.category))];

  const filteredTerms = useMemo(() => {
    return glossaryTerms.filter(term => {
      const matchesSearch = term.term.toLowerCase().includes(searchTerm.toLowerCase()) ||
        term.definition.toLowerCase().includes(searchTerm.toLowerCase());
      const matchesCategory = selectedCategory === 'all' || term.category === selectedCategory;
      return matchesSearch && matchesCategory;
    });
  }, [searchTerm, selectedCategory, glossaryTerms]);

  return (
    <div className="min-h-screen py-12">
      <div className="container mx-auto px-4">
        <div className="max-w-5xl mx-auto">
          <motion.div
            initial={{ opacity: 0, y: -20 }}
            animate={{ opacity: 1, y: 0 }}
            className="text-center mb-12"
          >
            <h1 className="section-title text-4xl">Glossary & Jargon Buster</h1>
            <p className="text-gray-600 text-lg">
              Searchable dictionary of investing terms with examples and simple explanations
            </p>
          </motion.div>

          {/* Controls */}
          <div className="card mb-8">
            {/* Search Bar */}
            <div className="relative mb-6">
              <FaSearch className="absolute left-4 top-1/2 transform -translate-y-1/2 text-gray-400" />
              <input
                type="text"
                placeholder="Search terms... (e.g., 'EPS', 'ratio', 'margin')"
                value={searchTerm}
                onChange={(e) => setSearchTerm(e.target.value)}
                className="w-full pl-12 pr-4 py-4 border-2 border-gray-300 rounded-lg focus:ring-2 focus:ring-primary focus:border-transparent text-lg"
              />
            </div>

            <div className="flex flex-col md:flex-row gap-4 items-center justify-between">
              {/* Category Filter */}
              <div className="flex flex-wrap gap-2">
                {categories.map(category => (
                  <button
                    key={category}
                    onClick={() => setSelectedCategory(category)}
                    className={`px-4 py-2 rounded-lg font-medium transition-all ${selectedCategory === category
                        ? 'bg-primary text-white shadow-md'
                        : 'bg-gray-100 text-gray-700 hover:bg-gray-200'
                      }`}
                  >
                    {category === 'all' ? 'All Categories' : category}
                  </button>
                ))}
              </div>

              {/* Simple Mode Toggle */}
              <button
                onClick={() => setSimpleMode(!simpleMode)}
                className={`px-6 py-3 rounded-lg font-semibold transition-all flex items-center gap-2 ${simpleMode
                    ? 'bg-yellow-400 text-gray-900 shadow-lg'
                    : 'bg-white border-2 border-gray-300 text-gray-700 hover:bg-gray-50'
                  }`}
              >
                <FaLightbulb />
                {simpleMode ? 'Expert Mode' : 'Explain Like I\'m 15'}
              </button>
            </div>
          </div>

          {/* Results Count */}
          <div className="mb-4 text-gray-600">
            Showing {filteredTerms.length} of {glossaryTerms.length} terms {searchTerm && `for "${searchTerm}"`}
          </div>

          {/* Terms List */}
          <div className="space-y-4">
            {filteredTerms.map((term, index) => (
              <motion.div
                key={index}
                initial={{ opacity: 0, y: 10 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ delay: index * 0.05 }}
                className="card hover:shadow-xl transition-shadow"
              >
                <div className="flex items-start justify-between mb-3">
                  <div>
                    <h3 className="text-xl font-bold text-gray-900">{term.term}</h3>
                    <span className="inline-block mt-1 px-3 py-1 bg-blue-100 text-blue-700 text-xs font-semibold rounded-full">
                      {term.category}
                    </span>
                  </div>
                  <FaBook className="text-primary text-2xl" />
                </div>

                {simpleMode ? (
                  <div className="bg-yellow-50 border-l-4 border-yellow-400 p-4 rounded mb-4">
                    <div className="flex items-start gap-2">
                      <FaLightbulb className="text-yellow-600 mt-1 flex-shrink-0" />
                      <p className="text-gray-800 font-medium">{term.simple}</p>
                    </div>
                  </div>
                ) : (
                  <p className="text-gray-700 mb-4">{term.definition}</p>
                )}

                <div className="grid md:grid-cols-2 gap-4 mt-4">
                  <div className="bg-blue-50 p-4 rounded-lg border border-blue-200">
                    <p className="text-xs font-semibold text-blue-900 mb-2">EXAMPLE</p>
                    <p className="text-sm text-gray-700">{term.example}</p>
                  </div>

                  <div className="bg-green-50 p-4 rounded-lg border border-green-200">
                    <p className="text-xs font-semibold text-green-900 mb-2">FORMULA</p>
                    <p className="text-sm text-gray-700 font-mono">{term.formula}</p>
                  </div>
                </div>

                {simpleMode && (
                  <details className="mt-4">
                    <summary className="cursor-pointer text-sm text-primary font-medium hover:underline">
                      Show technical definition
                    </summary>
                    <p className="mt-2 text-sm text-gray-600 bg-gray-50 p-3 rounded">
                      {term.definition}
                    </p>
                  </details>
                )}
              </motion.div>
            ))}
          </div>

          {filteredTerms.length === 0 && (
            <div className="text-center py-12">
              <p className="text-gray-500 text-lg">No terms found matching your search.</p>
              <button
                onClick={() => {
                  setSearchTerm('');
                  setSelectedCategory('all');
                }}
                className="mt-4 text-primary hover:underline"
              >
                Clear filters
              </button>
            </div>
          )}
        </div>
      </div>
    </div>
  );
};

export default Glossary;
